/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package suppliermonitoring_classes;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.io.*;

/**
 *
 * @author Elaine
 */
public class Supplier_Monitoring_GUI extends javax.swing.JFrame {
private void clearItemFields() {
    ItemIDtxt.setText("");
    ItemNameTxt.setText("");
    ItemcategoryTxt.setText("");
    itemCodeTxt.setText("");
}
// Helper to clear Supplier input fields
private void clearSupplierFields() {
    SupplierIDtxt.setText("");
    SFullNametxt.setText("");
    Addresstxt.setText("");
    Phonetxt.setText("");
}
// Helper to clear Delivery input fields
private void clearDeliveryFields() {
    DeliverIDtxt.setText("");
    Consignortxt.setText("");
    Pricnetxt.setText("");
    Consignortxt.setText("");
    Datetxt.setText("");
}
    /**
     * Creates new form OOP
     */
    public Supplier_Monitoring_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        ItemBtn = new javax.swing.JButton();
        DeliverBtn = new javax.swing.JButton();
        SupplierBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ItemPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ItemIDtxt = new javax.swing.JTextField();
        itemCodeTxt = new javax.swing.JTextField();
        ItemNameTxt = new javax.swing.JTextField();
        ItemcategoryTxt = new javax.swing.JTextField();
        SaveItemBtn = new javax.swing.JButton();
        updItemBtn = new javax.swing.JButton();
        DeleteItemBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        expitembtn = new javax.swing.JButton();
        SupplierPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        SupplierIDtxt = new javax.swing.JTextField();
        Addresstxt = new javax.swing.JTextField();
        SFullNametxt = new javax.swing.JTextField();
        Phonetxt = new javax.swing.JTextField();
        SaveSupBtn = new javax.swing.JButton();
        updSupplierBtn = new javax.swing.JButton();
        deleteSupBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        expSupbtn = new javax.swing.JButton();
        DeliverPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        DeliverIDtxt = new javax.swing.JTextField();
        Consignortxt = new javax.swing.JTextField();
        saveDeliBtn = new javax.swing.JButton();
        updDeliBtn = new javax.swing.JButton();
        DeleteDeliBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantitxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        datetxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        expDeliBtn = new javax.swing.JButton();
        SupIdDropBox = new javax.swing.JComboBox<>();
        ItemIDSupBox = new javax.swing.JComboBox<>();
        SuppNameDBox = new javax.swing.JComboBox<>();
        ItemNameBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ItemBtn.setText("Item Record");
        ItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBtnActionPerformed(evt);
            }
        });

        DeliverBtn.setText("Supplier Record");
        DeliverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliverBtnActionPerformed(evt);
            }
        });

        SupplierBtn.setText("Deliver Record");
        SupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ItemBtn)
                .addGap(173, 173, 173)
                .addComponent(DeliverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(SupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemBtn)
                    .addComponent(DeliverBtn)
                    .addComponent(SupplierBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Code", "Item Name", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ItemIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemIDtxtActionPerformed(evt);
            }
        });

        itemCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCodeTxtActionPerformed(evt);
            }
        });

        ItemNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameTxtActionPerformed(evt);
            }
        });

        ItemcategoryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemcategoryTxtActionPerformed(evt);
            }
        });

        SaveItemBtn.setText("SAVE");
        SaveItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveItemBtnActionPerformed(evt);
            }
        });

        updItemBtn.setText("UPDATE");
        updItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updItemBtnActionPerformed(evt);
            }
        });

        DeleteItemBtn.setText("DELETE");
        DeleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Item Record");

        jLabel8.setText("Category");

        jLabel9.setText("Item Name");

        jLabel10.setText("Item Code");

        jLabel11.setText("Item ID");

        expitembtn.setText("EXPORT");

        javax.swing.GroupLayout ItemPanelLayout = new javax.swing.GroupLayout(ItemPanel);
        ItemPanel.setLayout(ItemPanelLayout);
        ItemPanelLayout.setHorizontalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemcategoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ItemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(itemCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(ItemIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addComponent(SaveItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(expitembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        ItemPanelLayout.setVerticalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemPanelLayout.createSequentialGroup()
                        .addComponent(expitembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemcategoryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Item Record", ItemPanel);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Suppler Full Name", "Address", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        Phonetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonetxtActionPerformed(evt);
            }
        });

        SaveSupBtn.setText("SAVE");
        SaveSupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveSupBtnActionPerformed(evt);
            }
        });

        updSupplierBtn.setText("UPDATE");
        updSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updSupplierBtnActionPerformed(evt);
            }
        });

        deleteSupBtn.setText("DELETE");
        deleteSupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Supplier Record");

        jLabel13.setText("Supplier ID");

        jLabel14.setText("Supplier Full Name");

        jLabel15.setText("Address");

        jLabel16.setText("Phone Number");

        expSupbtn.setText("EXPORT");

        javax.swing.GroupLayout SupplierPanelLayout = new javax.swing.GroupLayout(SupplierPanel);
        SupplierPanel.setLayout(SupplierPanelLayout);
        SupplierPanelLayout.setHorizontalGroup(
            SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SFullNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupplierIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addGroup(SupplierPanelLayout.createSequentialGroup()
                        .addComponent(SaveSupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expSupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        SupplierPanelLayout.setVerticalGroup(
            SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupplierPanelLayout.createSequentialGroup()
                .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SupplierPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13))
                    .addGroup(SupplierPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(expSupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SupplierPanelLayout.createSequentialGroup()
                        .addComponent(SupplierIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(5, 5, 5)
                        .addComponent(SFullNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(4, 4, 4)
                        .addComponent(Addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(2, 2, 2)
                        .addComponent(Phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(SupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveSupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updSupplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteSupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier Record", SupplierPanel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Delivery ID", "Supplier ID", "Item ID", "Consignor", "Supplier Name", "Item Name", "Quantity", "Price", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        saveDeliBtn.setText("SAVE");
        saveDeliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDeliBtnActionPerformed(evt);
            }
        });

        updDeliBtn.setText("UPDATE");
        updDeliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updDeliBtnActionPerformed(evt);
            }
        });

        DeleteDeliBtn.setText("DELETE");
        DeleteDeliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDeliBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Deliver Record");

        jLabel2.setText("Delivery ID");

        jLabel3.setText("Supplier ID");

        jLabel4.setText("Item ID");

        jLabel5.setText("Consignor");

        jLabel6.setText("Supplier Full Name");

        jLabel17.setText("Date");

        jLabel18.setText("Item Name");

        jLabel19.setText("Price");

        jLabel20.setText("Quantity");

        expDeliBtn.setText("EXPORT");

        SupIdDropBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ItemIDSupBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SuppNameDBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ItemNameBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout DeliverPanelLayout = new javax.swing.GroupLayout(DeliverPanel);
        DeliverPanel.setLayout(DeliverPanelLayout);
        DeliverPanelLayout.setHorizontalGroup(
            DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeliverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeliverPanelLayout.createSequentialGroup()
                        .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DeliverPanelLayout.createSequentialGroup()
                                .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(DeliverIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(quantitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(datetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                        .addComponent(pricetxt, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(SupIdDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemIDSupBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Consignortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DeliverPanelLayout.createSequentialGroup()
                                        .addComponent(saveDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DeleteDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SuppNameDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DeliverPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(expDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72))
                    .addGroup(DeliverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        DeliverPanelLayout.setVerticalGroup(
            DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeliverPanelLayout.createSequentialGroup()
                .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeliverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeliverPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(expDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DeliverPanelLayout.createSequentialGroup()
                        .addComponent(DeliverIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SupIdDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemIDSupBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Consignortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuppNameDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(5, 5, 5)
                        .addComponent(ItemNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DeliverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteDeliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Deliver Record", DeliverPanel);

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 0, 48)); // NOI18N
        jLabel21.setText("SUPPLIER MONITORING");

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeliverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliverBtnActionPerformed
         jTabbedPane1.setSelectedIndex(1);
         
    }//GEN-LAST:event_DeliverBtnActionPerformed

    private void ItemNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameTxtActionPerformed

    private void SupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierBtnActionPerformed
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_SupplierBtnActionPerformed

    private void SaveItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveItemBtnActionPerformed
    String id = ItemIDtxt.getText().trim();
    String name = ItemNameTxt.getText().trim();
    String category = ItemcategoryTxt.getText().trim();
    String code = itemCodeTxt.getText().trim();

    if (id.isEmpty() || name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Item ID and Item Name are required!");
        return;
    }

    Items existingItem = null;
    for (Items item : Main.getItems()) {
        if (item.getItemID().equals(id)) {
            existingItem = item;
            break;
        }
    }

    if (existingItem == null) {
        Items newItem = new Items(id, name, 0, 0);
        newItem.setItemCategory(category);
        Main.getItems().add(newItem);
        JOptionPane.showMessageDialog(this, "New item added!");
    } else {
        existingItem.setItemName(name);
        existingItem.setItemCategory(category);
        JOptionPane.showMessageDialog(this, "Item updated!");
    }
    clearItemFields();
    loadItemTable();  
        
    }//GEN-LAST:event_SaveItemBtnActionPerformed

    private void itemCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeTxtActionPerformed

    private void ItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBtnActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_ItemBtnActionPerformed

    private void saveDeliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDeliBtnActionPerformed
    String id = DeliverIDtxt.getText().trim();
    String consignor = Consignortxt.getText().trim();
    String priceStr = Pricnetxt.getText().trim();
    String quantityStr = Consignortxt.getText().trim();
    String date = Datetxt.getText().trim();

    if (id.isEmpty() || consignor.isEmpty() || priceStr.isEmpty() || quantityStr.isEmpty() || date.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all delivery fields.");
        return;
    }

    double price;
    int quantity;
    try {
        price = Double.parseDouble(priceStr);
        quantity = Integer.parseInt(quantityStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Price must be a decimal and Quantity must be an integer.");
        return;
    }

    Delivers existingDelivery = null;
    for (Delivers d : Main.getDeliveries()) {
        if (d.getDeliverID().equals(id)) {
            existingDelivery = d;
            break;
        }
    }

    if (existingDelivery == null) {
        Delivers newDeli = new Delivers(id, "", consignor, "", quantity, price, date);
        Main.getDeliveries().add(newDeli);
        JOptionPane.showMessageDialog(this, "New delivery added.");
    } else {
        existingDelivery.setConsignor(consignor);
        existingDelivery.setPrice(price);
        existingDelivery.setQuantity(quantity);
        existingDelivery.setDate(date);
        JOptionPane.showMessageDialog(this, "Delivery updated!");
    }
    clearDeliveryFields();
    loadDeliveryTable();  // Refresh table
        
        
        
        
        
        
    }//GEN-LAST:event_saveDeliBtnActionPerformed

    private void ItemcategoryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemcategoryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemcategoryTxtActionPerformed

    private void ItemIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemIDtxtActionPerformed

    private void PhonetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonetxtActionPerformed

    private void updDeliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updDeliBtnActionPerformed
     StringBuilder sb = new StringBuilder();
    for (Delivers d : Main.getDeliveries()) {
        sb.append("ID: ").append(d.getDeliverID())
          .append(", Consignor: ").append(d.getConsignor())
          .append(", Price: ").append(d.getPrice())
          .append(", Quantity: ").append(d.getQuantity())
          .append(", Date: ").append(d.getDate())
          .append("\n");
    }
    JOptionPane.showMessageDialog(this, sb.length() == 0 ? "No deliveries found." : sb.toString(), "Deliveries", JOptionPane.INFORMATION_MESSAGE);
}

private void DeleteDeliBtnActionPerformed(java.awt.event.ActionEvent evt) {
    String id = DeliverIDtxt.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Delivery ID to delete.");
        return;
    }

    Delivers toRemove = null;
    for (Delivers d : Main.getDeliveries()) {
        if (d.getDeliverID().equals(id)) {
            toRemove = d;
            break;
        }
    }

    if (toRemove != null) {
        Main.getDeliveries().remove(toRemove);
        JOptionPane.showMessageDialog(this, "Delivery deleted.");
        clearDeliveryFields();
    } else {
        JOptionPane.showMessageDialog(this, "Delivery ID not found.");
    }   
    }//GEN-LAST:event_updDeliBtnActionPerformed

    private void SaveSupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveSupBtnActionPerformed
    String id = SupplierIDtxt.getText().trim();
    String fullName = SFullNametxt.getText().trim();
    String address = Addresstxt.getText().trim();
    String phone = Phonetxt.getText().trim();

    if(id.isEmpty() || fullName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Supplier ID and Full Name required.");
        return;
    }

    Supplier existingSupplier = null;
    for(Supplier sup : Main.getSuppliers()) {
        if(sup.getSupplierID().equals(id)) {
            existingSupplier = sup;
            break;
        }
    }

    if(existingSupplier == null) {
        Supplier newSup = new Supplier(id, fullName, "", phone, address);
        Main.getSuppliers().add(newSup);
        JOptionPane.showMessageDialog(this, "New supplier added!");
    } else {
        existingSupplier.setSupplierName(fullName);
        existingSupplier.setAddress(address);
        existingSupplier.setPhoneNumber(phone);
        JOptionPane.showMessageDialog(this, "Supplier updated!");
    }
    clearSupplierFields();
        
        
        
        
        
        
        
    }//GEN-LAST:event_SaveSupBtnActionPerformed

    private void updSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updSupplierBtnActionPerformed
   StringBuilder sb = new StringBuilder();
    for (Supplier s : Main.getSuppliers()) {
        sb.append("ID: ").append(s.getSupplierID())
          .append(", Name: ").append(s.getSupplierName())
          .append(", Address: ").append(s.getAddress())
          .append(", Phone: ").append(s.getPhoneNumber())
          .append("\n");
    }
    JOptionPane.showMessageDialog(this, sb.length() == 0 ? "No suppliers found." : sb.toString(), "Suppliers", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updSupplierBtnActionPerformed

    private void deleteSupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupBtnActionPerformed
    String id = SupplierIDtxt.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Supplier ID to delete.");
        return;
    }

    Supplier toRemove = null;
    for (Supplier s : Main.getSuppliers()) {
        if (s.getSupplierID().equals(id)) {
            toRemove = s;
            break;
        }
    }

    if (toRemove != null) {
        Main.getSuppliers().remove(toRemove);
        JOptionPane.showMessageDialog(this, "Supplier deleted.");
        clearSupplierFields();
    } else {
        JOptionPane.showMessageDialog(this, "Supplier ID not found.");
    }   
    }//GEN-LAST:event_deleteSupBtnActionPerformed

    private void DeleteDeliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDeliBtnActionPerformed
    String id = DeliverIDtxt.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Delivery ID to delete.");
        return;
    }

    Delivers toRemove = null;
    for (Delivers d : Main.getDeliveries()) {
        if (d.getDeliverID().equals(id)) {
            toRemove = d;
            break;
        }
    }

    if (toRemove != null) {
        Main.getDeliveries().remove(toRemove);
        JOptionPane.showMessageDialog(this, "Delivery deleted.");
        clearDeliveryFields();
    } else {
        JOptionPane.showMessageDialog(this, "Delivery ID not found.");
    }
    }//GEN-LAST:event_DeleteDeliBtnActionPerformed

    private void updItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updItemBtnActionPerformed
    StringBuilder sb = new StringBuilder();
    for(Items item : Main.getItems()) {
        sb.append("ID: ").append(item.getItemID())
          .append(", Name: ").append(item.getItemName())
          .append(", Category: ").append(item.getItemCategory())
          .append("\n");
    }
    JOptionPane.showMessageDialog(this, sb.length()==0?"No items found":sb.toString(), "All Items", JOptionPane.INFORMATION_MESSAGE);
}

private void DeleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {
    String id = ItemIDtxt.getText().trim();
    if(id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Item ID to delete.");
        return;
    }
    Items toRemove = null;
    for(Items item : Main.getItems()) {
        if(item.getItemID().equals(id)) {
            toRemove = item;
            break;
        }
    }
    if(toRemove != null) {
        Main.getItems().remove(toRemove);
        JOptionPane.showMessageDialog(this, "Item deleted successfully.");
        clearItemFields();
    } else {
        JOptionPane.showMessageDialog(this, "No item found with this ID.");
    } 
    }//GEN-LAST:event_updItemBtnActionPerformed

    private void DeleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemBtnActionPerformed
    String id = ItemIDtxt.getText().trim();
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter Item ID to delete.");
        return;
    }

    Items toRemove = null;
    for (Items item : Main.getItems()) {
        if (item.getItemID().equals(id)) {
            toRemove = item;
            break;
        }
    }

    if (toRemove != null) {
        Main.getItems().remove(toRemove);
        JOptionPane.showMessageDialog(this, "Item deleted successfully.");
        clearItemFields();
    } else {
        JOptionPane.showMessageDialog(this, "Item ID not found.");
    }
    }//GEN-LAST:event_DeleteItemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_Monitoring_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_Monitoring_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_Monitoring_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_Monitoring_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_Monitoring_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Addresstxt;
    private javax.swing.JTextField Consignortxt;
    private javax.swing.JButton DeleteDeliBtn;
    private javax.swing.JButton DeleteItemBtn;
    private javax.swing.JButton DeliverBtn;
    private javax.swing.JTextField DeliverIDtxt;
    private javax.swing.JPanel DeliverPanel;
    private javax.swing.JButton ItemBtn;
    private javax.swing.JComboBox<String> ItemIDSupBox;
    private javax.swing.JTextField ItemIDtxt;
    private javax.swing.JComboBox<String> ItemNameBox;
    private javax.swing.JTextField ItemNameTxt;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JTextField ItemcategoryTxt;
    private javax.swing.JTextField Phonetxt;
    private javax.swing.JTextField SFullNametxt;
    private javax.swing.JButton SaveItemBtn;
    private javax.swing.JButton SaveSupBtn;
    private javax.swing.JComboBox<String> SupIdDropBox;
    private javax.swing.JComboBox<String> SuppNameDBox;
    private javax.swing.JButton SupplierBtn;
    private javax.swing.JTextField SupplierIDtxt;
    private javax.swing.JPanel SupplierPanel;
    private javax.swing.JTextField datetxt;
    private javax.swing.JButton deleteSupBtn;
    private javax.swing.JButton expDeliBtn;
    private javax.swing.JButton expSupbtn;
    private javax.swing.JButton expitembtn;
    private javax.swing.JTextField itemCodeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField quantitxt;
    private javax.swing.JButton saveDeliBtn;
    private javax.swing.JButton updDeliBtn;
    private javax.swing.JButton updItemBtn;
    private javax.swing.JButton updSupplierBtn;
    // End of variables declaration//GEN-END:variables
}
